import type { Evento, GalleryItem, Princess, StoriaItem } from "@/types";

export const SITE = {
  nome: "Princess Academy",
  payoff: "Magical Party Experience",
  claim: "Trasformiamo ogni festa in una favola.",
  email: "magia@princess-academy.it",
  telefono: "+39 02 8736 0000",
  whatsapp: "+39 345 000 0000",
  indirizzo: "Via delle Fiabe 12, Milano",
  orari: "Lun – Sab · 9:00 – 19:00",
};

/** Dati dimostrativi — placeholder eleganti, nessun nome reale. */
export const PRINCESS_DEMO: Princess[] = [
  {
    slug: "aurora-fiaba",
    nome: "Aurora",
    personaggio: "La Principessa del Mattino",
    ruolo: "Principessa · Canto & Accoglienza",
    descrizione: "Dolce e luminosa, apre ogni festa con un inchino e una canzone.",
    biografia: [
      "Aurora è la prima ad accogliere i piccoli ospiti: un ingresso scenografico, una canzone cantata dal vivo e un momento dedicato a ogni festeggiato.",
      "Ama i laboratori di portamento da vera principessa e la cerimonia della coroncina, pensata per far sentire ogni bambina protagonista.",
    ],
    specialita: ["Accoglienza fiabesca", "Canto dal vivo", "Cerimonia della coroncina"],
    colori: { from: "#F28CC6", to: "#A50E66" },
    iniziale: "A",
    social: { instagram: "#", tiktok: "#" },
    demo: true,
  },
  {
    slug: "celeste-incanto",
    nome: "Celeste",
    personaggio: "La Fata dei Desideri",
    ruolo: "Fata · Magia & Truccabimbi",
    descrizione: "Con bacchetta e polvere di stelle trasforma il trucco in pura magia.",
    biografia: [
      "Celeste guida il momento della trasformazione: trucco delicato, glitter biodegradabile e acconciature da favola.",
      "Chiude ogni festa con il rituale dei desideri: ogni bambino affida una stellina al cielo.",
    ],
    specialita: ["Truccabimbi fiabesco", "Rituale dei desideri", "Baby dance magica"],
    colori: { from: "#E8CC76", to: "#C7147D" },
    iniziale: "C",
    demo: true,
  },
  {
    slug: "serena-perla",
    nome: "Serena",
    personaggio: "La Principessa del Lago",
    ruolo: "Principessa · Danza & Spettacolo",
    descrizione: "Elegante e teatrale, porta in festa un mini-spettacolo coreografato.",
    biografia: [
      "Serena porta in scena un elegante mini-spettacolo di danza con coinvolgimento dei bambini.",
      "Perfetta per matrimoni ed eventi pubblici, con valzer dei fiori e passerella reale.",
    ],
    specialita: ["Mini-spettacolo", "Valzer dei fiori", "Passerella reale"],
    colori: { from: "#F7B9DE", to: "#7E0C4F" },
    iniziale: "S",
    demo: true,
  },
  {
    slug: "luna-stellata",
    nome: "Luna",
    personaggio: "La Guardiana delle Stelle",
    ruolo: "Principessa · Lettura & Sogni",
    descrizione: "Racconta fiabe sotto un cielo di stelline luminose.",
    biografia: [
      "Luna crea l'angolo dei sogni: lettura animata, nanna fiabesca e buonanotte magica.",
      "Ideale per feste pomeridiane e pigiama party con caccia alle stelline.",
    ],
    specialita: ["Lettura animata", "Caccia alle stelline", "Pigiama party"],
    colori: { from: "#DFB954", to: "#5C0A3B" },
    iniziale: "L",
    demo: true,
  },
];

export const EVENTI: Evento[] = [
  {
    slug: "princess-party",
    titolo: "Princess Party",
    categoria: "Firma Academy",
    descrizione: "Il format originale: ingresso reale, trasformazione, giochi e incoronazione finale.",
    dettagli:
      "Due interpreti, scaletta costruita sull'età dei bambini, colonna sonora fiabesca e coordinamento con genitori e location.",
    durata: "2 – 3 ore",
    servizi: ["Ingresso scenografico", "Trucco & acconciatura", "Giochi a tema", "Incoronazione"],
    prezzo: "da € 390",
    disponibili: true,
    icone: "crown",
    gradiente: "from-princess-500 via-princess-600 to-princess-800",
  },
  {
    slug: "compleanni",
    titolo: "Compleanni da Favola",
    categoria: "Compleanni",
    descrizione: "Il giorno più atteso diventa una storia con la festeggiata protagonista.",
    dettagli: "Torta scenografica, taglio torta cantato, dedica personalizzata e foto ricordo con cornice oro.",
    durata: "2 ore",
    servizi: ["Dedica personalizzata", "Taglio torta cantato", "Foto ricordo", "Regalo Academy"],
    prezzo: "da € 290",
    disponibili: true,
    icone: "cake",
    gradiente: "from-gold-400 via-princess-500 to-princess-700",
  },
  {
    slug: "matrimoni",
    titolo: "Matrimoni & Cerimonie",
    categoria: "Matrimoni",
    descrizione: "Accoglienza bambini, damigelle da favola e show elegante per gli sposi.",
    dettagli: "Servizio discreto e coordinato con wedding planner, angolo bimbi presidiato e valzer augurale.",
    durata: "Su misura",
    servizi: ["Angolo bimbi", "Damigelle da favola", "Valzer augurale", "Coordinamento planner"],
    prezzo: "Preventivo su misura",
    disponibili: true,
    icone: "rings",
    gradiente: "from-ivory-dark via-gold-200 to-gold-500",
  },
  {
    slug: "aziendali",
    titolo: "Eventi Aziendali",
    categoria: "Eventi Aziendali",
    descrizione: "Family day, Natale aziendale e inaugurazioni con standard premium.",
    dettagli: "Team dedicato, schede di sicurezza, scaletta oraria precisa e report fotografico.",
    durata: "Mezza / intera giornata",
    servizi: ["Team dedicato", "Scaletta oraria", "Meet & greet", "Report fotografico"],
    prezzo: "Preventivo su misura",
    disponibili: true,
    icone: "building",
    gradiente: "from-princess-700 via-ink to-ink",
  },
  {
    slug: "feste-private",
    titolo: "Feste Private",
    categoria: "Feste private",
    descrizione: "Giardino, villa o terrazza: portiamo noi scenografia leggera e magia.",
    dettagli: "Sopralluogo, adattamento spazi, piano B in caso di pioggia e kit anti-stress per i genitori.",
    durata: "2 – 4 ore",
    servizi: ["Sopralluogo", "Scenografia leggera", "Animazione", "Piano B pioggia"],
    disponibili: true,
    icone: "home",
    gradiente: "from-princess-300 via-princess-500 to-princess-800",
  },
  {
    slug: "pubblici",
    titolo: "Eventi Pubblici & Piazze",
    categoria: "Eventi pubblici",
    descrizione: "Parate, accensioni luminarie e feste di città con palco.",
    dettagli: "Fonico e presentatore, gestione file e code, sicurezza e permessi supportati.",
    durata: "Su misura",
    servizi: ["Parata", "Show da palco", "Presentazione", "Gestione code"],
    disponibili: true,
    icone: "mic",
    gradiente: "from-gold-500 via-princess-600 to-princess-900",
  },
  {
    slug: "meet-greet",
    titolo: "Meet & Greet",
    categoria: "Meet & Greet",
    descrizione: "Foto perfette, code ordinate e sorrisi veri: l'incontro che resta nel cuore.",
    dettagli: "Set fotografico con cornice oro, assistente dedicato, tempistiche garantite per ogni famiglia.",
    durata: "1 – 3 ore",
    servizi: ["Set fotografico", "Assistente code", "Autografi fiabeschi", "Stampe ricordo"],
    prezzo: "da € 240",
    disponibili: true,
    icone: "camera",
    gradiente: "from-blush via-princess-300 to-princess-600",
  },
  {
    slug: "spettacoli",
    titolo: "Spettacoli",
    categoria: "Spettacoli",
    descrizione: "Un vero mini-musical da 30 o 50 minuti con costumi sartoriali.",
    dettagli: "Cast di 3-5 artisti, audio professionale, interazione e finale con neve di stelle.",
    durata: "30 / 50 min",
    servizi: ["Cast 3–5 artisti", "Audio pro", "Costumi sartoriali", "Finale stelle"],
    prezzo: "da € 690",
    disponibili: true,
    icone: "sparkles",
    gradiente: "from-princess-600 via-princess-700 to-ink",
  },
  {
    slug: "animazione",
    titolo: "Animazione Classica",
    categoria: "Animazione",
    descrizione: "Truccabimbi, palloncini, baby dance e caccia al tesoro con stile Academy.",
    dettagli: "Perfetta come integrazione o formato leggero per budget contenuti senza rinunciare all'eleganza.",
    durata: "1,5 – 2 ore",
    servizi: ["Truccabimbi", "Palloncini", "Baby dance", "Caccia al tesoro"],
    prezzo: "da € 190",
    disponibili: true,
    icone: "wand",
    gradiente: "from-gold-300 via-gold-500 to-princess-600",
  },
  {
    slug: "su-misura",
    titolo: "Eventi Su Misura",
    categoria: "Personalizzati",
    descrizione: "Gender reveal, battesimi, anniversari: scriviamo insieme la tua favola.",
    dettagli: "Call creativa gratuita, moodboard, prove costumi e regia dedicata il giorno dell'evento.",
    durata: "Su misura",
    servizi: ["Call creativa", "Moodboard", "Regia dedicata", "Prove costumi"],
    disponibili: true,
    icone: "heart",
    gradiente: "from-princess-400 via-gold-400 to-princess-700",
  },
];

export const STORIA: StoriaItem[] = [
  {
    anno: "2020",
    titolo: "La nascita (esempio)",
    descrizione: "Dato dimostrativo: le prime feste tra amiche, con due costumi cuciti a mano e una cassa di glitter.",
  },
  {
    anno: "2021",
    titolo: "Le prime esperienze (esempio)",
    descrizione: "Dato dimostrativo: i primi compleanni a domicilio e il passaparola delle mamme.",
  },
  {
    anno: "2022",
    titolo: "La crescita (esempio)",
    descrizione: "Dato dimostrativo: arriva il format Princess Party da due ore con scaletta scritta.",
    evidenza: true,
  },
  {
    anno: "2023",
    titolo: "Nuove Princess (esempio)",
    descrizione: "Dato dimostrativo: il cast cresce, nascono i laboratori di portamento e trucco.",
  },
  {
    anno: "2024",
    titolo: "Nuovi eventi (esempio)",
    descrizione: "Dato dimostrativo: matrimoni, piazze e il primo mini-musical da palco.",
  },
  {
    anno: "2025",
    titolo: "Nuovi progetti (esempio)",
    descrizione: "Dato dimostrativo: Academy aperta a nuove interpreti con formazione dedicata.",
  },
];

export const GALLERIA: GalleryItem[] = [
  { id: "g1", titolo: "Ingresso reale", categoria: "Princess Party", evento: "Princess Party", data: "2025", gradiente: "from-princess-400 to-princess-700", icona: "crown", altezza: "alta" },
  { id: "g2", titolo: "Taglio torta cantato", categoria: "Compleanni", evento: "Compleanno", data: "2025", gradiente: "from-gold-300 to-princess-500", icona: "cake", altezza: "media" },
  { id: "g3", titolo: "Valzer augurale", categoria: "Matrimoni", evento: "Matrimonio", data: "2024", gradiente: "from-ivory-dark via-gold-200 to-gold-500", icona: "rings", altezza: "bassa" },
  { id: "g4", titolo: "Neve di stelle", categoria: "Spettacoli", evento: "Mini-musical", data: "2024", gradiente: "from-princess-600 to-ink", icona: "sparkles", altezza: "alta" },
  { id: "g5", titolo: "Trucco fatato", categoria: "Eventi", evento: "Festa privata", data: "2025", gradiente: "from-blush to-princess-400", icona: "wand", altezza: "media" },
  { id: "g6", titolo: "Family day", categoria: "Eventi Aziendali", evento: "Azienda", data: "2024", gradiente: "from-princess-700 to-ink", icona: "building", altezza: "bassa" },
  { id: "g7", titolo: "Coroncine d'oro", categoria: "Princess Party", evento: "Princess Party", data: "2025", gradiente: "from-gold-400 to-princess-700", icona: "crown", altezza: "media" },
  { id: "g8", titolo: "Parata in piazza", categoria: "Eventi", evento: "Città", data: "2023", gradiente: "from-princess-300 to-princess-600", icona: "mic", altezza: "alta" },
  { id: "g9", titolo: "Foto ricordo", categoria: "Compleanni", evento: "Meet & Greet", data: "2025", gradiente: "from-princess-500 to-princess-800", icona: "camera", altezza: "bassa" },
];

export const CATEGORIE_GALLERIA = [
  "Tutti",
  "Eventi",
  "Princess Party",
  "Compleanni",
  "Matrimoni",
  "Eventi Aziendali",
  "Spettacoli",
] as const;

export const TIPOLOGIE_EVENTO = [
  "Princess Party",
  "Compleanno",
  "Matrimonio / Cerimonia",
  "Evento aziendale",
  "Festa privata",
  "Evento pubblico",
  "Meet & Greet",
  "Spettacolo",
  "Animazione",
  "Evento personalizzato",
] as const;
